### ISSUE TITLE
关于entity, word embedding的问题

### ISSUE THREAD

**Issue by dylanchen0114** [chenghuige/mind#4]
大佬太牛了！
我看到在config文件里，use_entity_pretrain与use_word_pretrain都是设置的false，实际最后训练中应该不是这样的吧？
另外, Encoders 中，entity与entity_type使用的sum的add_n方法，这个也是最终的方法吗？
非常感谢你的分享，希望你能抽空解答～

**Comment by chenghuige** [comment]
@dylanchen0114 训练的时候都是True finetune，entity应该使用的是self attention pooling。
