### ISSUE TITLE
wenzheng/utils/melt/

### ISSUE THREAD

**Issue by leidejun** [chenghuige/mind#7]
wenzheng/utils/melt/中找不到的代码会公开吗？

**Comment by chenghuige** [comment]
@leidejun  将会完整开源在pikachu2项目中

**Comment by leidejun** [comment]
好的，谢谢前辈

**Comment by liangliang-max** [comment]
完整开源在pikachu2项目，这个项目在哪可以给一下具体的链接吗，谢谢。@leidejun ，@chenghuige

**Comment by leidejun** [comment]
> 

https://github.com/chenghuige/pikachu2

**Comment by leidejun** [comment]
> > 
> 
> https://github.com/chenghuige/pikachu2
